import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import "node_modules/locomotive-scroll/dist/locomotive-scroll.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Chakra_Petch({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className=" md:p-4  px-2 md:px-10 text-white text-opacity-90">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
