"use client"; // to import client side only modules

import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import "node_modules/locomotive-scroll/dist/locomotive-scroll.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { useEffect } from "react";
import { AnimatePresence } from "framer-motion";

const inter = Chakra_Petch({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <AnimatePresence mode='wait'> 
      <body className={inter.className} >
        <Navbar />
        <main className="md:p-4  overflow-hidden md:px-10 text-white text-opacity-90">
          {children}
        </main>
        <Footer />
      </body>
      </AnimatePresence>
    </html>
  );
}
